# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2025'
email: annethessen@gmail.com
full_name: Anne Thessen
gh_action_docs_preview: false
gh_action_pypi: true
github_org: diatomsRcool
license: MIT
project_description: Testing agentic AI for NSRR project
project_name: sleep-cde-schema
project_slug: sleep_cde_schema

